# The Story Line is random......very random
# And may contain a Harry Potter spoilerm just a small one, but if you haven't read the book that came before the Deathly hallows then don't play this game or watched the film fot that matter 
# It's good enough                                #no it isnt -jack    # No....it really is -Jake
import time     #Imports time from the libary
import random   #Imports Random from the libary 
def PrintShia():
  print(":::::::::::::::::::::::::::::::::::::::::##::::::::::::::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::::::::::::::##::::::::::::::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::::::::###############:::::::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::############################::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::#####################################:::::::::::::")
  time.sleep(0.5)
  print("::::::::::::::::::::::###########################################::::::::::")
  time.sleep(0.5)
  print("::::::::::::::::::::###########################################::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::#############################################:::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::##############################################::::::::::::::")
  time.sleep(0.5)
  print("::::::::::::::######################CCCCC#####################:::::::::::::")
  time.sleep(0.5)
  print("::::::::::::###############CCCCC:::::    ::CC#####CCCCCCCC#####::::::::::::")
  time.sleep(0.5)
  print(":::::::::::############CC:::::::                           ::C##:::::::::::")
  time.sleep(0.5)
  print("::::::::::##########CCC:::::::                                :C#::::::::::")
  time.sleep(0.5)
  print(":::::::::##########CCCC:::::                                   :C#:::::::::")
  time.sleep(0.5)
  print("::::::::##########CC::::::::                                     ::::::::::")
  time.sleep(0.5)
  print("::::::::###JN####CC:::::::                                        :::::::::")
  time.sleep(0.5)
  print("::::::::#########CC:::::::                                         ::::::::")
  time.sleep(0.5)
  print("::::::::#########CC:::::::                                         ::::::::")
  time.sleep(0.5)
  print("::::::::#########CCC::::::                                         ::::::::")
  time.sleep(0.5)
  print("::::::::#########CCCC::::::                                        ::::::::")
  time.sleep(0.5)
  print("::::::::#########CCCC:::CCCC#C#######C:                            ::::::::")
  time.sleep(0.5)
  print("::::::::#########CCCCC#################C           C##########C:   ::::::::")
  time.sleep(0.5)
  print("::::::::###########C#####C:::::::CCC#CCC::        C###CCCCC::C##C::::::::::")
  time.sleep(0.5)
  print("::::::::###############CC::::::CCC#####CC:       CCCC:::       C#C:::::::::")
  time.sleep(0.5)
  print(":::::::C########C##C###C###CC####CC:C####CC     :CCCCC:::  : : ::C:::::::::")
  time.sleep(0.5)
  print("::::::##C::C####CCCCCC###########  CCC:C#C:      ::C#####CCC:::::::::::::::")
  time.sleep(0.5)
  print("::::::##C:C:###CCCCC:::CCCCC:CCC     :::C:        :  C###:::CC:: :  :::::::")
  time.sleep(0.5)
  print("::::::##C:#####CCCC::::::::::::::: : :::::         :::::::::::     ::::::::")
  time.sleep(0.5)
  print("::::::##:##:C###CCC:::               :::::                       ::::::::::")
  time.sleep(0.5)
  print(":::::::#::::::##CCCC::              ::::::                       ::::::::::")
  time.sleep(0.5)
  print(":::::::#::###:####CC::::           ::CCC::                       ::::::::::")
  time.sleep(0.5)
  print(":::::::#CC#::######CC:::            ::::::                        :::::::::")
  time.sleep(0.5)
  print("::::::::##::::#####CC:::            CCC##CC:   ::               : :::::::::")
  time.sleep(0.5)
  print(":::::::::#::::###CCCCC::::         ::C##::CCC::CC:             :  :::::::::")
  time.sleep(0.5)
  print("::::::::::###CC##CCCCC:::: :       :::::::::                   :  :::::::::")
  time.sleep(0.5)
  print(":::::::::::::::##CCCCCC:::::       : :::                      :: ::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::C#CCCCCC::::: :     :::                       ::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::C##CCCCCC:::::: :   :CCCCCCC:::::             ::::::::::::::")
  time.sleep(0.5)
  print("::::::::::::::::C##CCCCC:::::::::CCCCCCCCCCCCCC:CCC::      ::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::C##CCCCCC:::::: :::::::         :         ::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::C##CCCCCC:::: :::::CCCCCCC:::::       ::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::C##CCCCCCC:::::::::::C:::::       ::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::C##CCCCC::::: :                :::C:::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::C##CCCC:::                 :::C:::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::C##CC::::               ::C:::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::C###CCCCC:: : : :   CCC:::::::::::::::::::::::")
  time.sleep(0.5)
  print("::::::::::::::::::::::::::::::::C###############C::::::::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::::::::C#########C:::::::::::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::::::::::::::##:::::::::::::::::::::::::::::::")
  time.sleep(0.5)
  print(":::::::::::::::::::::::::::::::::::::::::##::::::::::::::::::::::::::::::::")
  time.sleep(0.5)
  print("Cave Johnson Appeared") # Portal reference, there will be lots of thease refrences as it annoys Joey
  time.sleep(2)
  print("Oh! Its actually Shia")
  #Ascii art from http://www.noah.org/wiki/ASCII_art
def Credits():
  time.sleep(1)
  print("Coded By Jake") #Jake  @JakeNTech on Twitter and Instagram
  time.sleep(1)
  print("Spell Checked By Joey (actually Jack did pretty much all 1.2k lines + grammar and i'm not even a member of this group...I also left alot of comments in the source code)") #Joesph / Jack
  time.sleep(1)
  print("Tested by Izan")#Izan Not that it was tested that much
  #Connor was there too...
  #Sometimes....
  time.sleep(1)
  print("Connor was there too.")
  time.sleep(1)
  print("When he wasn't **ill*")
  time.sleep(2)
  print("Based on the Song Shia LeBeouf - Rob Canter") #https://www.youtube.com/watch?v=o0u4M6vppCI   #Yes, I did also buy it for my iPod -Jake
  input("Press enter to close")
  exit()
def loading(): # Loading screen
  print("MadBox studios is proud to present.....")
  time.sleep(2)
  print("Shia LeBeouf")
  PrintShia()
  time.sleep(2)
  print("A text based decision game")
  time.sleep(2)
  print("'Game of the Century'- PCGamer")
  time.sleep(2)
  print("Clap")
  time.sleep(1)
  print("Clap")
  time.sleep(1)
  print("Clap")
  time.sleep(2)
  print("-The Daily mail")
  time.sleep(1)
  print("But who cares what they think?")
  time.sleep(2)
  print("Approved by Shia LaBeouf")
  time.sleep(2)
  print("Valve couldn't do much better")
  time.sleep(1)
  print("(We made those bits up)")
  time.sleep(2)
  print("By playing this game you agree not to sue anyone")
def MainMenu(): # Main Menu....if it wasn't clear enough already
  global User_Name #Makes the username a global veriable
  User_Name = str(input("Please enter a user name for the game: ")).title()
  # I took insperation from the hidden messages at TVR #you spelt inspiration wrong -jack
  # But thease aren't as rude #and "these" -jack
  #lol
  if User_Name == "Sans": #i added the .title() for you guys because it caused me physical pain to see it without -jack # It's allready there.....can't you read!
    print("nope") #incase you though that this was undertale
    time.sleep(2)
    End_Dead()
    exit()
  elif User_Name == "Shia":
    print("Nice hack there!") #You won't be able to get away with it, it would be good if you could play as shia but that will come at a later date -Jake
    time.sleep(2)
    End_Dead()
    exit()
  elif User_Name == "Jack": #well then -jack # You have a reputation lol -Jake
    print("Try not to destroy this game Jack!")
    time.sleep(2)
  elif User_Name == "Joey":
    print("SPELL CHECK ME FIRST!") #already done it -jack #Thanks, although EA will now be loking into it! -Jake
    time.sleep(2)
  elif User_Name == "Tester":
    print("You must be trying to hack the game!")
    time.sleep(2)
    print("Nice try though")
    time.sleep(2)
    End_Dead()
    exit()
  elif User_Name =="":
    print("You can't be anonymous all the time!")
    time.sleep(2)
    print("You failed before the game even started")
    time.sleep(2)
    print("LOL")
    time.sleep(2)
    End_Dead()
    exit()
  elif User_Name == "Jake":
    print("Hello Lord Jake!")
    time.sleep(0.5)
    print("Hows the bike holding up?")
    time.sleep(2)
    print("Not that well I assume")
    time.sleep(2)
    print("What about the macbook with the dead GPU?")
    time.sleep(2)
    for i in range (1,10):
      print(".")
    print("I thought as much")
    time.sleep(2)
  else:
    print("Welcome",User_Name,"You will enjoy this game!")
    print("\n")
    time.sleep(1)
def End_Dead():#Ending if you die
  print("Sorry But you have died")
  time.sleep(0.5)
  print("                                 ____________")
  time.sleep(0.5)
  print("                                |            |")
  time.sleep(0.5)
  print("                                |            |")
  time.sleep(0.5)
  print("                                |   _     _  |")
  time.sleep(0.5)
  print("                                |  |_) | |_) |")
  time.sleep(0.5)
  print("                                |  | \ | |   |")
  time.sleep(0.5)
  print("                                |            |")
  time.sleep(0.5)
  print("                 ______.______%_|            |__________  _____")
  time.sleep(0.5)
  print("               _/                                             |")
  time.sleep(0.5)
  print("              |                  ",User_Name,"                |")
  time.sleep(0.5)
  print("             |_____.-._________              ____/|___________|")
  time.sleep(0.5)
  print("                                | Awhile ago |")
  time.sleep(0.5)
  print("                                |      Now   |")
  time.sleep(0.5)
  print("                                |            |")
  time.sleep(0.5)
  print("                                |            |")
  time.sleep(0.5)
  print("                                |            |")
  time.sleep(0.5)
  print("                                |   _        <")
  time.sleep(0.5)
  print("                                |__/         |")
  time.sleep(0.5)
  print("                                 / `--.      |")
  time.sleep(0.5)
  print("                               %|            |%")
  time.sleep(0.5)
  print("                           |/.%%|          -< @%%%")
  time.sleep(0.5)
  print("                           `\%`@|     v      |@@%@%%   ")
  time.sleep(0.5)
  print("                         .%%%@@@|%    |    % @@@%%@%%%%")
  time.sleep(0.5)
  print("                    _.%%%%%%@@@@@@%%_/%\_%@JB%%@@@@@@@%%%%%%")
  LeaderBoard = open("Leaderboard.txt","a")
  LeaderBoard.write("\n")#Makes new line in leaderboard.txt
  LeaderBoard.write(User_Name)#Writes username to leaderboard.txt
  LeaderBoard.write("-Died")#Wirtes that the user died in leaderboard.txt
  LeaderBoard.close()#CLoses the text file
  Credits()#Plays the acknowlagements
def End_Alive(): #Ending If you won
  for i in range (1,50):
    print("Clap")#sarcastic clapping
  print("Well Done")
  time.sleep(2)
  print("""
                                                          ..
                               ,,,                         MM .M
                           ,!MMMMMMM!,                     MM MM  ,.
   ., .M                .MMMMMMMMMMMMMMMM.,          'MM.  MM MM .M'
 . M: M;  M          .MMMMMMMMMMMMMMMMMMMMMM,          'MM,:M M'!M'
;M MM M: .M        .MMMMMMMMMMMMMMMMMMMMMMMMMM,         'MM'...'M
 M;MM;M :MM      .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.       .MMMMMMMM
 'M;M'M MM      MMMMMM  MMMMMMMMMMMMMMMMM  MMMMMM.    ,,M.M.'MMM'
  MM'MMMM      MMMMMM @@ MMMMMMMMMMMMMM @@ MMMMMMM.'M''MMMM;MM'
 MM., ,MM     MMMMMMMM  MMMMMMMMCLMMMMMM  MMMMMMMMM      '.MMM
 'MM;MMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      'MMM
  ''.'MMM'  .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMM
   MMC      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      'MMMM
  .MM      :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM''MMM       MMMMM
  MMM      :M  'MMMMMMMMMMMMM.MMMMM.MMMMMMMMMM'.MM  MM:M.    'MMMMM
 .MMM   ...:M: :M.'MMMMMMMMMMMMMMMMMMMMMMMMM'.M''   MM:MMMMMMMMMMMM'
AMMM..MMMMM:M.    :M.'MMMMMMMMMMMMMMMMMMMM'.MM'     MM''''''''''''
MMMMMMMMMMM:MM     'M'.M'MMMMMMMMMMMMMM'.MC'M'     .MM
 '''''''''':MM.       'MM!M.'M-M-M-M'M.'MM'        MMM
            MMM.            'MMMM!MMMM'            .MM
             MMM.             '''   ''            .MM'
              MMM.                               MMM'
               MMMM            ,.J.JJJJ.       .MMM'
                MMMM.       'JJJJJJJ'JJJM   CMMMMM
                  MMMMM.    'JJJJJJJJ'JJJ .MMMMM'
                    MMMMMMMM.'  'JJJJJ'JJMMMMM'
                      'MMMMMMMMM'JJJJJ JJJJJ'
                         ''MMMMMMJJJJJJJJJJ'
                              'JJJJJJJJ')
  """)
  time.sleep(1)
  print("It's all cupcakes and rainbows for you now")
  time.sleep(1)
  print("There will be a show about this on CBS")
  time.sleep(1)
  print("You Have won")
  LeaderBoard = open("Leaderboard.txt","a")
  LeaderBoard.write("\n")
  LeaderBoard.write(User_Name)
  LeaderBoard.write("-Survived")
  LeaderBoard.close()
  time.sleep(1)
  Credits()
#The game starts
loading() # Calls the loading screen
MainMenu() #Plays the main menu
for i in range(1,50):
  print("\n")
print("====START======") # the game starts
time.sleep(1)
print("You're walking in the woods")
time.sleep(2)
print("There's no one around and your phone is dead")
time.sleep(1)
print("""
                 -
                | |
                | |
                | |
            _.._| |          
     __.--"" __ ----.__    
   .'//   .-"  "-.   \ `,  
  : :'  .'.  :;  ,`.  `; ; 
 /; ;  /  T. $$ ,P  \  : : 
/: :  ;    T.:;,P    :  ; ;
)| | :      Nokia     ; | |
`j | :.--------------.: | |
 ; ; | XXX        XXX | : :
 ; ; | XXX        XXX | : :
 | | |       XX       | | |
 | | |       XX       | | |
 : : | /\/\/\/\/\/\/\ | ; ;
 : : :________________: ; ;
  ; ;__    _...._    __: : 
  | ;  "-./ ,--, \,-"  : | 
  | '._   \ ;  : /   _.' | 
  :  __`-. `."",' .-'__  ; 
   ;`.__> `.J__L.' <__.':  
   ;.--._   .--.   _.--,:  
   |`.__.' `.__.' `.__.'|  
   |.--._   .--.   _.--,|  
   |`.__.' `.__.' `.__.'|  
   |.--._   .--.   _.--,|  
   ;`.__.' `.__.' `.__.':  
  : .--._   .--.   _.--, ; 
  ; `.__.' `.__.' `.__.' : 
  ;                      : 
  '--..__          __..--' 
         ''''''''''
""")
time.sleep(2)
print("Out of the corner of your eye, you spot him")
time.sleep(3)
print("SHIA LABEOUF")
time.sleep(3)
print("Shia is approaching")
time.sleep(2)
print("He is getting out of his corvett")
time.sleep(2)
print("Which means he is a murderer")
time.sleep(1)
print("======First Choice=====")
time.sleep(1)
print("You have 3 choices")
print("1: Do you walk towards him, 2: Walk away, 3: Stay where you are")
time.sleep(2)
FirstChoice = int(input("Your Decision, and quick! "))
for i in range (1,25):
  print("\n")
if FirstChoice == 1:
  print("You walk towards Shia.")
  time.sleep(2.5)
  print("He Grunts...and stares")
  time.sleep(2.5)
  print("He reaches into his pocket")
  time.sleep(1)
  print("He pulls out a......")
  time.sleep(2.5)
  print("....")
  time.sleep(2.5)
  print("A pen")
  time.sleep(2.5)
  print("He signs your forehead")
  time.sleep(2.5)
  print("He gets back into his corvett")
  time.sleep(2.5)
  print("He says 'I will see you around kid'")
  time.sleep(2.5)
  print("You are star-struck!")
  time.sleep(2)
  End_Alive()
  exit()
elif FirstChoice == 3:
  print("You slowly look up")
  time.sleep(2.5)
  print("Shia looks down on you")
  time.sleep(2.5)
  print("He raises his hand")
  time.sleep(2.5)
  print("He knocks you over")
  time.sleep(2)
  End_Dead()
  exit()
elif FirstChoice > 3:
  print("You chose incorrectly, You suffer the consequences")
  End_Dead()
  exit()
print ("He's following you about thirty feet back ")
time.sleep(2)
print("He gets down on all fours and breaks into a sprint")
time.sleep(2)
print("He is making up lost ground!")
time.sleep(2)
print("Shia LaBeouf")
time.sleep(2)
print("You are looking for your V12 XJS Jag")
time.sleep(2)
print("You reach the end of the car park")
time.sleep(2)
print("====Second Choice=====")
print("You have three options")
time.sleep(2)
print("1- Run into the river or 2- Run towards Shia or 3- Turn around to face Shia")
SecondChoice = int(input("Hurry decide now! "))
for i in range (1,25):
  print("\n")
if SecondChoice == 1:
  print("You jump the wall")
  time.sleep(1)
  print("Splash")
  time.sleep(1)
  print("Splash")
  time.sleep(1)
  print("The water is cold and icy")
  time.sleep(1)
  print("Your foot get pulled down")
  time.sleep(2)
  print("Your head goes under")
  time.sleep(2)
  print("Whats that you can feel??")
  time.sleep(2)
  print("A shopping trolly?")
  time.sleep(2)
  print("Why yes it is!")
  time.sleep(1)
  End_Dead()
  exit()
elif SecondChoice == 2 :
  print("You start to rub your feet on the floor")
  time.sleep(2)
  print("Like a Bull about to charge")
  time.sleep(2)
  print("You make a 'GRRRRRRRRR' sound")
  time.sleep(2)
  print("As you run to shia, it starts it starts to become brighter outside.")
  time.sleep(2)
  print("Then you run into shia")
  time.sleep(2)
  print("Hold on a moment....")
  time.sleep(0.5)
  print(".")
  time.sleep(0.5)
  print(".")
  time.sleep(0.5)
  print(".")
  time.sleep(0.5)
  print("You have just run through Shia")
  time.sleep(2)
  print("As you turn around he is gone")
  time.sleep(2)
  print("That must have been a dream")
  time.sleep(2)
  print("But no it wasn't")
  time.sleep(2)
  print("You can now see your Jagggggg")
  time.sleep(2)
  print("Hu!")
  time.sleep(2)
  print("Shia's corvett has gone too")
  End_Alive()
  exit()
elif SecondChoice == 3:
  time.sleep(0.5)
  print("You slowly turn around")
elif SecondChoice > 3:
  print("You stand there not knowing what to do")
  time.sleep(1)
  print("You brace yourself")
  time.sleep(2)
  End_Dead()
  exit()
time.sleep(2)
print("He comes closer towards you")
time.sleep(1)
print("You can see blood on his face")
time.sleep(1)
print("Bloddy 'l")
time.sleep(2)
print("There is blood everywhere")
time.sleep(1)
print("=====Third Choice=====")
print("You have three options")
time.sleep(0.5)
print("1-Offer first Aid, 2-Run to the right, 3-Stand Still")
ThirdChoice = int(input("Quick, he is at an immense pace: "))
for i in range (1,25):
  print("\n")
if ThirdChoice == 1:
  print("You offer medical support")
  time.sleep(1)
  print("Shia Keeps running")
  time.sleep(1)
  print("You and Shia fall into the river")
  time.sleep(1)
  print("Shia holds your head under the water")
  time.sleep(1)
  End_Dead()
  exit()
elif ThirdChoice == 3:
  time.sleep(1)
  print("Shia Keeps running")
  time.sleep(1)
  print("You and Shia fall into the river")
  time.sleep(1)
  print("Shia holds your head under the water")
  time.sleep(1)
  End_Dead()
  exit()
elif ThirdChoice > 3:
  print("You stand there not knowing what to do")
  time.sleep(1)
  print("You brace yourself")
  time.sleep(2)
  End_Dead()
  exit()
print("You run to the right")
time.sleep(1)
print("Your start getting a stitch")
time.sleep(1)
print("No, its just your keys digging into your thunder thigh")
time.sleep(1)
print("You're running for your life")
time.sleep(2.5)
print("You are literally running for your life!")
time.sleep(2)
print("You glance around to see Shia")
time.sleep(2.5)
print("What's that in his hand")
time.sleep(1)
print("No way, thats a knife")
time.sleep(1)
print("You keep running for your life.....")
time.sleep(1)
print("It's Shia LeBeouf")
time.sleep(2)
print("Lurking in the shadows")
time.sleep(2)
print("Hollywood Superstar...")
time.sleep(1)
print("Tom Cruise?")
time.sleep(1)
print("No, sorry....it's Shia LeBeouf")
time.sleep(2)
print("Somewhere in the woods")
time.sleep(3)
print("It's Shia LeBeouf")
time.sleep(2)
print("Eating all the people")
time.sleep(2)
print("Actual Canibal Shia LeBeouf")
time.sleep(3)
print("It's dark now")
time.sleep(2)
print("Shia Is no where to be seen")
time.sleep(2)
print("But now you are lost")
time.sleep(2)
print("All you can see is trees")
time.sleep(2)
print("But what's that...")
time.sleep(2)
print("In the distance")
time.sleep(2)
print("It has a light on")
time.sleep(1)
print("It takes you a moment or two to make sure it's not doggers in a Vectra") #wtf? -jack #It where people go and have 'fun' in there cars in a car park at night, with other peope - Jake
time.sleep(2)
print("It has the shape of a cottage")
time.sleep(2)
print("Yes! It is a cottage")
time.sleep(2)
print("======Forth Choice=====")
print("Run to the cottage?")
time.sleep(1)
print("Type yes or no")
ForthChoice = str(input("You're scared, hurry up and make your mind up. ")).title()
for i in range (1,25):
  print("\n")
if ForthChoice == "No" :
    print("You ponder your life")
    time.sleep(2)
    print("But Shia has come back")
    time.sleep(1)
    End_Dead()
    exit()
elif ForthChoice == "Yes":
  time.sleep(1)
  print("You have decided to go to the cottage")
  time.sleep(2)
else:
  print("You can't make a decision that doesn't exist")
  time.sleep(1)
  End_Dead()
  exit()
print("You move carefully towards the cottage")
time.sleep(1)
print("You hear a mechanical snap")
time.sleep(2)
print("AGH, YOU'RE STUCK IN A BEAR TRAP!")
time.sleep(2)
print("""
                                     _.-'
                                 _.-'
                 _____________.-'________________
                /         _.-' O                /|
               /  i====_======O      __________/ /
              /  / _.-'      O      /     _   /|/
             /  / | p       o      /     (   / /
            /  /           O      /_________/ /
           /  L===========O                /|/
          /______________O________________/ /
        |________________________________|/
That's not a bear trap but you get the idea
""")
time.sleep(3)
print("But a bit bigger than that one")
time.sleep(2)
print("The hinge on this thing could do with some WD-40") #get in the bin -jack #What??? Should I have used WD-39 insted? -Jake
time.sleep(1)
print("======Fifth Choice=====")
print("You now have three options")
time.sleep(1)
print("1-Lay there and hope that someone comes to help, 2- Gnaw off your leg, 3- Shout to Shia LaBeouf for help")
time.sleep(1)
FifthChoice = int(input("Hurry, your leg really hurts: "))
for i in range (1,25):
  print("\n")
if FifthChoice == 1:
  print("You wait")
  time.sleep(1)
  print("And wait")
  time.sleep(2)
  print("And wait")
  time.sleep(1)
  print("The pain becomes too much")
  time.sleep(1)
  print("Your brain starts shutting down")
  time.sleep(2)
  print("You can't prevent it")
  time.sleep(2)
  print("You have just had the equivalent of a BSoD") #*facepalm* -jack #It's better then "You freezz to update" -Jake
  End_Dead()
  exit()
elif FifthChoice == 3:
  print("You yell out")
  time.sleep(2)
  print("'SHIA'")
  time.sleep(2)
  print("'SHIA.....HELP!'")
  time.sleep(2)
  print("You see a pair of feet infront of you...")
  time.sleep(2)
  print("It's Shia LaBeouf")
  time.sleep(2)
  print("He's still holding the knife")
  time.sleep(2)
  print("Now you are restrained")
  time.sleep(2)
  print("He looks down on you")
  time.sleep(2)
  print("Holding the knife")
  time.sleep(2)
  print("He takes a strike")
  time.sleep(2)
  print("You have seen Shia LaBeouf")
  time.sleep(2)
  End_Dead()
  exit()
elif FifthChoice > 3:
  print("An invalid selection, you pay the price")
  time.sleep(2)
  End_Dead()
  exit()
print("You move your face to your leg")
time.sleep(2)
print("You take your first bite")
time.sleep(2)
print("Nom!")
time.sleep(2)
print("Nom!")
time.sleep(2)
print("Ouch!")
time.sleep(1)
print("That doesn't taste nice")
time.sleep(2)
print("Hopping to the porch")
time.sleep(1)
print("Quiet")
time.sleep(0.5)
print("Quiet")
time.sleep(2)
print("Now you're on the door step")
time.sleep(2)
print("Sitting inside, you see Shia LaBeouf")
time.sleep(2)
print("Sharpening an axe")
time.sleep(2)
print("Shia LaBeouf")
time.sleep(2)
print("=====Sixth Choice=====")
print("Want to enter?")
SixthChoice = str(input("Hurry you're not good at standing on one leg? ")).upper()
for i in range (1,25):
  print("\n")
if SixthChoice == "NO":
  print("You fall over and hurt your arm")
  time.sleep(1)
  print("You clamber to your feet")
  time.sleep(2)
  print("You see a foot coming towards you")
  time.sleep(3)
  print("The last thing you feel is Shia's cold axe going across your face")
  time.sleep(2)
  End_Dead()
  exit()
elif SixthChoice == "YES":
  time.sleep(2)
  print("You walk through the open door")
  time.sleep(2)
else:
  print("Your inability to decide causes you to make a odd but satisfying hissing noise") #??? -jack #You don't get this???? -Jake
  time.sleep(2)
  print("You see Shia getting up")
  time.sleep(2)
  print("OMG there is blood everywhere again")
  time.sleep(2)
  print("Oh wait...it's yours, bloddy 'l")
  End_Dead()
  exit()
print("You are sneaking up behind him")
time.sleep(2)
print("Strangling hollywood star")
time.sleep(1)
print("Shia LeBeouf")
time.sleep(2)
print("Fighting for your life")
time.sleep(2)
print("With Shia LaBeouf")
time.sleep(2)
print("You start to wrestle over a knife")
time.sleep(2)
print("With Shia LaBeouf")
time.sleep(2)
print("You manage to get the knife from Shia LaBeouf")
time.sleep(2)
print("You have a few seconds to decide what to do")
time.sleep(2)
print("In the heat of the moment you decide to stab Shia LaBeouf")
time.sleep(2)
print("====Seventh Choice=====")
SeventhChoice = str(input("Where do you stab him? ")).title()
for i in range (1,25):
  print("\n")
if SeventhChoice == "No-where":
  print("Your heart gets the better of you")
  time.sleep(1)
  print("Shia respects that")
  time.sleep(2)
  print("But not for long")
  time.sleep(2)
  End_Dead()
  exit()
elif SeventhChoice == "Head":
  print("You have clearly over estimated the power of a human with a knife")
  time.sleep(2)
  print("But you still try anyway")
  time.sleep(2)
  print("Shia manages to pick up a grandmother clock") #ok then -jack  #It's a bit smaller then a grandfather clock.-Jake
  time.sleep(2)
  print("He hit you with his clock")
  time.sleep(2)
  print("You have sustained a head injury")
  time.sleep(3)
  End_Dead()
  exit()
elif SeventhChoice == "Body":
    print("You're inability to specify where to stab someone breaks you")
    time.sleep(1)
    End_Dead()
    exit()
elif SeventhChoice == "Kidney":
  print("You have seen the video have't you!!!!!!")
  time.sleep(2)
  print("But that's ok....")
  time.sleep(2)
  print("We can forget that")
elif SeventhChoice == "Heart":
    print("You go to place the dagger in Shia's heart")
    time.sleep(2)
    print("You start saying 'Murderer' over and over again")
    time.sleep(2)
    print("You have a mental break down")
    time.sleep(2)
    print("Shia is dead, but you are suffering with guilt")
    time.sleep(2)
    print("You can't handle it")
    End_Dead()
    exit()
elif SeventhChoice == "Stomach":
    print("You stab shia in the stomac")
    time.sleep(2)
    print("The smell of rotten food is enough to finish you off") #so u just die from a bad smell, wow. -jack # Yes, it's a really bad one -Jake
    time.sleep(1)
    End_Dead()
elif SeventhChoice == "Back":
  print("You try to stab him in the back...")
  time.sleep(2)
  print("But the surface area is too large")
  time.sleep(2)
  print("Shia has escaped from your hold")
  time.sleep(2)
  print("As he gets up he hits the roaring log fire")
  time.sleep(2)
  print("It would appear that his hands are made of asbestos") #why -jack   # Why not? -Jake
  time.sleep(1)
  print("He picks up a flaming log and places it near the door")
  time.sleep(2)
  print("But you have spotted an open window......")
  time.sleep(2)
  print("And on the other side you have spotted your Jaaaaaaaaaaaaag")
  print("""
       .----------.
      /            \       
    _(.-. _...._ .-.)_   
   (_)`-' __()__ `-'(_)  
  (....__|EASTER|__....) 
   | |    ~~~~~~    | |   
   `-'              `-'
  """)
  time.sleep(2)
  print("You go to climb out the window while Shia's back is turned")
  time.sleep(2)
  print("You manage to squeeze your body through the open window")
  time.sleep(2)
  print("As you run towards your car you trip over something")
  time.sleep(2)
  print("You see somehting that looks a bit like the entrance to the Chamber of Secrets from the Harry Potter films") #were you on meth while writing this? -jack #Nah. Just not thinking -Jake
  time.sleep(2)
  print("As you move towards the door you see...")
  time.sleep(2)
  print("Hagrid.......")
  time.sleep(2)
  print("But as you move closer it looks more like Professor Snape")
  time.sleep(2)
  print("After a few more meters you notice that its acutally Shia LeBeouf")
  time.sleep(2)
  print("He pulls a stick out of his pocket....")
  time.sleep(2)
  print("And kills you like Snape killing Dumbledore") #spoilers -jack   # Oh yeah, oh well, only like you spoling Rogue One for carl -Jake
  time.sleep(2)
  print("You think to yourself that this seems surreal")
  time.sleep(2)
  print("Well....it is")
  time.sleep(2)
  print("You have just finished day dreaming in school")
  time.sleep(2)
  print("Now get back to work!")
  End_Alive()
  exit()
elif SeventhChoice == "Foot":
  time.sleep(2)
  print("What did you think that was going to do?")
  time.sleep(2)
  print("You get on the floor to stab Shia in the foot")
  time.sleep(2)
  print("Shia manages to get an axe off the wall and kill you")
  time.sleep(2)
  End_Dead()
  exit()
elif SeventhChoice == "":
  time.sleep(2)
  print("Why can't you decide")
  time.sleep(2)
  print("You got this far")
  time.sleep(2)
  print("As Shia has said himself: 'JUST DO IT'-Shia LeBeouf")
  End_Dead()
  exit()
print("You stab him in the ",SeventhChoice)
time.sleep(2)
print("Safe at last from Shia LaBeouf")
time.sleep(2)
print("You gaze into the dark woods")
time.sleep(2)
print("With Blood gushing from your stump leg")
time.sleep(2)
print("You have beaten Shia LaBeouf")
time.sleep(5)
print("Wait....")
time.sleep(2)
print("........")
time.sleep(3)
print("He isn't Dead!")
time.sleep(2)
print("SHIA Suprise")
time.sleep(2)
print("There is a gun to your head")
time.sleep(2)
print("But you can do Jujutsu")#Not Going to lie but I had to google that to see how its spelt
time.sleep(1)
print("=====Eighth Choice=====")
EighthChoice = str(input("Want to use it? ")).upper()
for i in range (1,25):
  print("\n")
if EighthChoice == "NO":
  print("BANG!")
  time.sleep(1)
  print("You're on the floor")
  End_Dead()
  exit()
elif EighthChoice == "YES":
  print("Body slam Shia LaBeouf")
else:
  print("You can't answer properly to your own self-conscience")
  time.sleep(2)
  print("BANG!")
  time.sleep(1)
  print("You're on the floor")
  End_Dead()
  exit()
print("You are now having a fight")
time.sleep(2)
print("With Hollywood superstar Shia LaBeouf")
time.sleep(2)
print("You swing a punch at Shia LaBeouf")
time.sleep(2)
print("He tries to swing back")
time.sleep(2)
print("Your fight is heating up")
time.sleep(2)
print("You think about running away")
time.sleep(0.5)
print("=====Nineth Choice=====")
print("1- For run, 2- For stay and fight")
NinethChoice = int(input("This fight is like it's in a pub at closing time: "))
for i in range (1,25):
  print("\n")
if NinethChoice == 1:
  print("You crawl away")
  time.sleep(2)
  print("You have forgotten how fast Shia LaBeouf is")
  time.sleep(2)
  print("He punches where your leg used to be")
  time.sleep(2)
  End_Dead()
  exit()
elif NinethChoice > 2:
  print("You obviously can't decide")
  time.sleep(2)
  print("He punches where your leg used to be")
  time.sleep(2)
  print("Ouch!")
  time.sleep(1)
  print("That really hurt")
  End_Dead() #seriously wtf is happening -jack # The question is what's not happening -Jake
  exit()
time.sleep(2)
print("You try to swing an axe")
time.sleep(2)
print("At Shia LeBeouf")
time.sleep(2)
print("He blocks it on the right")
time.sleep(2)
print("He blocks it on the left")
time.sleep(2)
print("You manage to get his neck")
time.sleep(3)
print("You have just decapitated Shia LeBeouf")
time.sleep(5)
print("His head drops to the floor")
time.sleep(2)
print("With no emotion")
time.sleep(2)
print("Or noise")
time.sleep(3)
print("You stumble backwards")
time.sleep(2)
print("While catching your breath")
time.sleep(2)
print("You are finally safe from Shia LaBeouf")
time.sleep(5)
print("Or are you......")
time.sleep(2)
print("Un-needed suspence there Joey")
time.sleep(2)
for i in range (1,25):
  print("\n")
Ending_Route = random.randint(1,5)
#print(Ending_Route)
if Ending_Route == 1:
  print("No, he really is dead")
  time.sleep(2)
  print("You should probably get out now!")
  time.sleep(2)
  print("You don't want to be caught")
  time.sleep(2)
  print("Type Run to run away and leave Shia there; Help to phone for help or Hide to dispose of the head")
  TenthChoice = input("Hurry! You can hear the police! ").title()
  if TenthChoice == "Run":
    time.sleep(1)
    print("You drop the axe")
    time.sleep(1)
    print("You thumble for your keys")
    time.sleep(2)
    print("You feel the Jaguar keyring")
    time.sleep(2)
    print("You hop into your V12 XJS")
    time.sleep(2)
    print("You turn the key in the ignition")
    time.sleep(2)
    print("***Car engine turns over***")
    time.sleep(2)
    print("It happens again")
    time.sleep(2)
    print("OH No, the rozzers have arrived") #had to google this, gonna assume you meant rozzers instead of "rozers" -jack #Yeah, its a TG thing -Jake
    time.sleep(2)
    End_Dead()
    exit()
  elif TenthChoice == "Help":
    print("You see a Landline phone")
    time.sleep(2)
    print("You press the nine key")
    time.sleep(2)
    print("9")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("9")
    time.sleep(2)
    print("You Idiot....")
    time.sleep(2)
    print("Why give yourself in!")
    time.sleep(2)
    print("And you can't count")
    time.sleep(2)
    print("And.....")
    time.sleep(2)
    print("The phone is now coverd in your blood")
    time.sleep(2)
    print("The rozzers turn up")
    time.sleep(2)
    print("Oh NO!")
    time.sleep(2)
    End_Dead()
  elif TenthChoice == "Hide":
    print("You scramble to find a bag")
    time.sleep(2)
    print("You put the axe in your bag")
    time.sleep(2)
    print("Run to your Jag")
    time.sleep(2)
    print("And off you drive along the M4")
    time.sleep(2)
    print("But there is a diversion")
    time.sleep(2)
    print("So you end up on the A303")
    time.sleep(2)
    print("Phwoar!") #how did you spell "phwoar" "phwar" -jack # Carfully -Jake
    time.sleep(2)
    print("You are glad you bought a V12 XJS")
    time.sleep(2)
    End_Alive()
  else:
    print("You can't make your mind up")
    time.sleep(2)
    print("You have let yourself down")
    time.sleep(2)
    print("You got this far...and have failed")
    time.sleep(2)
    End_Dead()
    exit()
elif Ending_Route == 2:
  print("Shia suddenly disovles")
  time.sleep(2)
  print("It's like magic")
  time.sleep(2)
  print("The Blood from your hands is gone")
  time.sleep(2)
  print("Not Knowing what to do you walk back into the dark woods")
  time.sleep(2)
  print("They seem to have gone too")
  time.sleep(2)
  print("Wait.....")
  time.sleep(2)
  print("You have woken up in a Travel lodge")
  time.sleep(2)
  End_Alive()
elif Ending_Route == 3:
  print("You can't belive what you have just done...")
  time.sleep(2)
  print("But as it happens you are bad with guilt")
  time.sleep(2)
  print("You have handed yourself into the police")
  time.sleep(2)
  End_Dead()
elif Ending_Route == 4:
  print("You go to exit the cottage")
  time.sleep(2)
  print("But a strange picture above the fire place catches your interest")
  time.sleep(2)
  print("""
                          ,sdPBbs.
                        ,d$$$AA$$$b.
                       d$P'`Y'`Y'`?$b
                      d'    `  '  \ `b
                     /    |        \  \
                    /    / \       |   \
               _,--'        |      \    |
             /' _/          \   |        \
          _/' /'             |   \        `-.__
      __/'       ,-'    /    |    |     \      `--...__
    /'          /      |    / \     \     `-.           `\
   /   /;;,,__-'      /   /    \            \            `-.
  /  |;;;;;;;\                                             \

""")
  time.sleep(2)
  print("You have to imagine that that's a photo in a frame")
  print("You look behind the picture on the mantel piece")
  time.sleep(2)
  print("There is a safe")
  EleventhChoice = str(input("Want to look inside, as it's open? ")).title()
  if EleventhChoice == "Yes":
    print("You have a curious mind")
    time.sleep(2)
    print("You open the safe")
    time.sleep(2)
    print("CLICK!")
    time.sleep(2)
    print("The room is suddenly lit up gold")
    time.sleep(2)
    print("There is about 20 bit coins worth of gold in the safe")
    time.sleep(2)
    End_Alive()
    exit()
  elif EleventhChoice == "No":
    print("You are not curious enough to have a look to see what is in the safe")
    time.sleep(2)
    print("What was the point of you coming on this journey?")
    time.sleep(2)
    End_Dead()
  else:
    print("You got this far.....and you stopped trying")
    time.sleep(2)
elif Ending_Route == 5:
  print("As you leave the cottage in your Jaaaggggg")
  time.sleep(2)
  print("You start to get this funny feeling that something else is going to happen")
  time.sleep(2)
  print("As you start driving along you decide to cut a corner through a car park")
  time.sleep(2)
  print("But as you are going through you notice someting odd")
  time.sleep(2)
  print("Waitrose is being Ram-Raided") #stop -jack # We need to keep up with current events -Jake
  time.sleep(2)
  print("You swing your Jaggggg around and put on full beam")
  time.sleep(2)
  print("You scarmble for your phone to call the police...")
  time.sleep(2)
  print("But your phone has gone flat...")
  time.sleep(2)
  print("One of the Audi's start driving towards you....")
  time.sleep(2)
  print("Not knowing what to do, you floor the V12!")
  time.sleep(2)
  print("Now you're in a car chase with Shia LeBeouf's criminal mates")
  time.sleep(2)
  print("You manage to make it onto the A1")
  time.sleep(2)
  print("Your Jag is not only nicer then the Audi but more powerful")
  time.sleep(2)
  print("Once you can't see them anymore, you decide to pull over into some services")
  time.sleep(2)
  print("You approach a pay phone and call the police")
  time.sleep(2)
  print("You go to get back in your Jaaaaaggg to go home")
  time.sleep(2)
  print("But Shia's mates have formed a road block")
  time.sleep(2)
  End_Dead()
  exit()
else:
  print("This game has failed")
  time.sleep(2)
  print("Hacker.........")
  time.sleep(2)
  print("You broke it")
  time.sleep(1)
  print("EA will sue you soon")
  time.sleep(2)
  print("Direct all angry comments to shia.the.killer.labeouf@gmail.com") #That's a real email addres, the only thing is....I cant remember the password to it oops -Jake
  time.sleep(1)
  print("We should have done better") #yes you should. -jack # Yeah your right we should have done, prehaps a proper GUI and a combat system; Or we should have gone all out to make a undertale like game -Jake
  Credits()
  exit()
